### ISSUE TITLE
Docker File should be updated

### ISSUE THREAD

**Issue by johnwanggithub** [springjk/java-in-docker#1]
the Tomcat version in Dockfile for java-maven-tomcat should be updated.

**Comment by springjk** [comment]
Which version do you want?
And which version is the most popular for now.

> Tomcat mirrors
* <http://mirror.bit.edu.cn/apache/tomcat/>
* <http://mirrors.aliyun.com/apache/tomcat/>

**Comment by johnwanggithub** [comment]
用中文了。。。。里面的版本号错了，现在那个地址下面已经没有v8.0.41，有v8.0.43

**Comment by springjk** [comment]
错其实没错，只是他们删除了。

这也是我困惑的一个地方，不知为什么他们总是删除以前的版本，我今晚考虑下是用 CDN 解决还是每次跟随更新。你有什么建议吗？

**Comment by johnwanggithub** [comment]
你说的对，确实不是错误。还真没啥好的建议
