### ISSUE TITLE
不能连接数据库

### ISSUE THREAD

**Issue by johnwanggithub** [springjk/java-in-docker#2]
![2017-05-04 05 35 43 pm](https://cloud.githubusercontent.com/assets/3618122/25697997/baf499da-30ef-11e7-911c-9fd21440b3b5.png)
mysql的容器起不来，打开IP+port报错：数据库连接错误，是否更改了 docker-compose 默认的数据库配置？

**Comment by springjk** [comment]
是以前可以启动更新代码后现在不能启动了吗？

83c7f78 这次提交中确实修改了一些东西，但是理论上不会影响，如果是全新的使用，我在本地测试没有问题。

**Comment by johnwanggithub** [comment]
一直这样。不知道是不是yml文件的问题，
还是代码里面
con = DriverManager.getConnection("jdbc:mysql://mysql/docker", "root", "docker"); 这个地方写法问题。我在参考这个链接http://dchq.co/2/post/2015/09/docker-3-tier-java-app-nginx-tomcat-mysql-automation-on-any-cloud.html 修改yml文件试试看

**Comment by springjk** [comment]
新拉的代码也启动不了吗？是否更改过数据库密码？

如果确认数据可以不需要的话，删除代码目录下的 mysql 存储，`rm -rf /data/mysql `, 然后 `docker-compose down && docker-compose up -d`。

***注意，数据会清除。***

**Comment by johnwanggithub** [comment]
![2017-05-05 02 37 17 pm](https://cloud.githubusercontent.com/assets/3618122/25735747/ed00bbe2-319f-11e7-8154-968e8d3419a6.png)
结果见上图，还是不行。我只改动过Dockerfile里的ENV TOMCAT_VERSION 8.0.43，没有更新过数据库密码

**Comment by springjk** [comment]
![image](https://cloud.githubusercontent.com/assets/7900609/25737848/80984d28-31ac-11e7-879d-9c090564c10f.png)
![image](https://cloud.githubusercontent.com/assets/7900609/25737866/9861d014-31ac-11e7-9ed3-f2186b7b28bf.png)
![image](https://cloud.githubusercontent.com/assets/7900609/25737885/aca2871c-31ac-11e7-910c-cdcc1e213cff.png)


我这里是正常的，你执行 `docker-compose up -d && docker-compose logs -f` 看下有没有什么错误输入。我觉得很有可能是你的 mysql 端口被占用。

**Comment by johnwanggithub** [comment]
![2017-05-05 06 18 00 pm](https://cloud.githubusercontent.com/assets/3618122/25741754/d2e7f774-31be-11e7-9809-be5428fb69d1.png)
初步看log好像是/var/lib/mysql/ 这个目录权限问题 @springjk

**Comment by johnwanggithub** [comment]
确实是上面说的目录权限问题，已解决@springjk
